config/routes.rb
Projektplattform::Application.routes.draw do
  get "notifications/index"
  get "statusupdates/index"

  devise_for :users
  
  resources :users
  resources :searchs
  resources :dashboards
  resources :statusupdates
  resources :roles
  resources :stages
  resources :notifications do
    collection do
      put :mark_as_read
    end
  end
  resources :jobs
    
  resources :projects do
    member do
      put :follow
      delete :unfollow
      delete :leave
      put :join
      post :apply
    end
    resources :media
  end
  
  root :to => "projects#index"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :sender, :class_name => "User"
  belongs_to :receiver, :class_name => "User"
  belongs_to :project
  
  def categories
    self.project.categories.map { |c| c.label }
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def create
    if params[:invitation]
      Notification.create(
        :sender_id=>current_user.id,
        :receiver_id=>User.find_by_name(params[:username]).id,
        :project_id=>params[:project_id],
        :isNew=>true,
        :html_tmpl_key=>"DECISION_TO_USER"
      )
    end
    redirect_to :back, :notice => "Die Einladung wurde verschickt."
  end

  def destroy
    @notification = Notification.find(params[:id])
    @receiver = @notification.sender_id
    @notification.destroy

    if !params[:notify].nil?
      @project = Project.find_by_id params[:project_id]
      
      Notification.create(
        :sender_id=>current_user.id,
        :receiver_id=>@receiver,
        :project_id=>@project.id,
        :isNew=>true,
        :html_tmpl_key=>params[:notify]
      )
    end
    
    respond_to do |format|
      format.js { render :nothing => true }
    end
  end
  
  def mark_as_read
    puts params
    unread_notifications = Notification.where(:receiver_id=>current_user.id)
    unread_notifications.each do |n|
        n.isNew = false
        n.save
    end
    redirect_to :back
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_invitation_form.html.erb
<!-- OVERLAY -->
<div id="overlaySendInvitation" class="overlay">
	<h1>Team erweitern - User einladen</h1>
	<a class="close" id="close"><%= image_tag 'close.png' %></a>
	<div class="content">
		<%= form_for Notification.new, :method => :post, :html => { :id => "invitation_form" } do |f| %>
			<%= hidden_field_tag :invitation, true %>
			<%= hidden_field_tag :project_id, @project.id %>
		  <%= text_field_tag :username, "", :class => "stdInpt" %>
		  <%= f.submit "Einladung schicken", :class => "stdBtn no2" %>
		<% end %>
	  <div class="clean"></div>
	</div>
</div>

<script type="text/javascript">
  $(function() {
    $('#invitation_form .stdInpt').autocomplete(<%=raw User.all.map { |u| u.name } %>);
  });
</script>

app/views/notifications/_overlay.html.erb
<div id="overlayNotifications" class="overlay nbtm">
	<h1>Notifications</h1>
  <%= link_to mark_as_read_notifications_path(@notifications), :method => :put, :id=>"close" do %>
    <%= image_tag 'close.png' %>
  <% end %>
	<div class="content scroll">
    <% if @notifications.nil? %><p class="no">keine Notifications vorhanden &hellip;</p><% end %>
    <ul>
  
      <% @notifications.each do |n| %>
        <li <% if n.isNew %>class="new"<% end %>>
          <!-- delete notification button -->
          <% if n.html_tmpl_key != 'DECISION_TO_USER' && n.html_tmpl_key != 'DECISION_TO_OWNER' %>
            <%= link_to image_tag('close-notice.png'), n, :method=>:delete, :class=>"delete_notification wcs", :remote=>true %>
          <% end %>
  
          <div class="<%= n.html_tmpl_key %>"><p>
          <% case n.html_tmpl_key %>
            <% when 'DECLINED' %>
                <%= link_to n.sender.name, n.sender, :class=>"name" %> hat die Einladung für das Projekt <%= link_to n.project.title, n.project, :class=>"projectover" %> abgelehnt.</p>
            <% when 'ACCEPTED_TO_USER' %>
                <%= image_tag "okmini.png", :class=>"left" %>Deine Bewerbung für das Projekt <%= link_to n.project.title, n.project, :class=>"projectover" %> wurde angenommen.</p>
             <% when 'DECLINED_TO_USER' %>
                Deine Bewerbung für das Projekt <%= link_to n.project.title, n.project, :class=>"projectover" %> wurde leider abgelehnt.</p>
             <% when 'USER_NEW' %>
                <%= image_tag "usermini.png", :class=>"left" %><%= link_to n.sender.name, n.sender, :class=>"name" %> ist jetzt Mitglied im Projekt <%= link_to n.project.title, n.project, :class=>"projectover" %>.</p>
             <% when 'USER_LEAVE' %>
                <%= link_to n.sender.name, n.sender, :class=>"name" %> hat das Projekt <%= link_to n.project.title, n.project, :class=>"projectover" %> verlassen.</p>
             <% when 'DECISION_TO_USER' %>
                Du wurdest in das Projekt <%= link_to n.project.title, n.project, :class=>"projectover" %> eingeladen.</p>
                <%= link_to "Bestätigen", join_project_path(n.project, :dtu=>true, :notification_id=>n.id), :method=>:put, :class=>"stdBtn no2" %>
                <%= link_to "Ablehnen", {:controller=>:notifications, :action=>:destroy, :id=>n.id, :notify=>"DECLINED", :project_id=>n.project.id}, :method => :delete, :class=>"delete_notification stdBtn", :remote=>true %><br />
             <% when 'DECISION_TO_OWNER' %>
                <%= link_to n.sender.name, n.sender, :class=>"name" %> möchte dem Projekt <%= link_to n.project.title, n.project, :class=>"projectover" %> beitreten.</p>
                <%= link_to "Akzeptieren", join_project_path(n.project, :receiver_id=>n.sender.id, :notification_id=>n.id), :method=>:put, :class=>"stdBtn no2" %>
                <%= link_to "Ablehnen", {:controller=>:notifications, :action=>:destroy, :id=>n.id, :notify=>"DECLINED_TO_USER", :project_id=>n.project.id}, :method => :delete, :class=>"delete_notification stdBtn", :remote=>true %><br />
            <% end %>
            
          <!-- additional informations for project -->
          <div class="project">
            <%= image_tag "arrup.png", :class=>"arr" %><%= image_tag n.project.icon_url, :class=>"pic" %>
            <h6><%= n.project.title %></h6>
            <p><span><%= trimString n.categories.join(', '), 25 %></span></p>
          </div>
          <sub class="date"><%= formatDate n.created_at, true, true %></sub>
        </div>
      </li>
    <% end %>
  </ul>
  <div class="clean"></div>
  </div>
</div>