config/routes.rb
Projektplattform::Application.routes.draw do
  get "notifications/index"
  get "statusupdates/index"

  devise_for :users
  
  resources :users
  resources :searchs
  resources :dashboards
  resources :statusupdates
  resources :roles
  resources :stages
  resources :notifications do
    collection do
      put :mark_as_read
    end
  end
  resources :jobs
    
  resources :projects do
    member do
      put :follow
      delete :unfollow
      delete :leave
      put :join
      post :apply
    end
    resources :media
  end
  
  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :status, :link, :description, :picture, :category_ids, :job_ids, :role_ids, :roles, :privace_setting_id, :show_update, :stage_ids, :isPublic
  
  
  has_and_belongs_to_many :categories
  has_many :jobs, :dependent => :destroy
  accepts_nested_attributes_for :jobs, :allow_destroy => true
  has_many :media
  has_many :images
  belongs_to :cover
  has_many :roles, :order => 'role DESC', :dependent => :destroy
  has_many :users, :through => :roles
  has_many :stages, :dependent => :destroy
  has_many :statusupdates
  has_one :privacy_setting

  after_update :post_statusupdate

  scope :is_public, where("isPublic = ?", true)
  scope :category, lambda { |category_label|
    joins(:categories).
    where(:categories => {:label => category_label}) 
  }
  scope :status, lambda { |status| 
    where(:status=>parse_status(status))
  }
  scope :sorted, order('created_at DESC')
  
  def self.parse_status status
    @status_names = { 
      "idea"          => "Idee", 
      "inprogress"    => "In Arbeit", 
      "finished"      => "Abgeschlossen", 
      "Idee"          => "idea", 
      "In Arbeit"     => "inprogress", 
      "Abgeschlossen" => "finished" 
    }
    @status_names[status]
  end
  
  # filter projects by category or status
  def self.filter_projects category, status
    if !category.nil? && !status.nil?
      Project.category(category).status(status)
    elsif !category.nil?
      Project.category(category)
    elsif !status.nil?
      Project.status(status)
    else 
      Project
    end
  end
  
  def cover_url
    if self.cover.nil?
      "/images/default_project_cover.jpg"
    else
      self.cover.asset.url(:cover)
    end
  end
  
  def icon_url
    if self.cover.nil?
      "/images/default_project_icon.jpg"
    else
      self.cover.asset.url(:small)
    end
  end

  def owner
    User.joins(:roles).where(:roles => { :role => "owner", :project_id => self.id }).first
  end
  
  def team owner=false
    if owner
      User.joins(:roles).where(:roles => { :role => ["member", "leader", "owner"], :project_id => self.id })
    else
      User.joins(:roles).where(:roles => { :role => ["member", "leader"], :project_id => self.id })
    end
  end
  
  def followers
    User.joins(:roles).where(:roles => { :role => "follower", :project_id => self.id })
  end

  def has_followers
    self.roles.where(:role => "follower" )
  end
  
  def has_members
    self.roles.where(:role => [ "owner", "leader", "member" ])
  end
  
protected
  def post_statusupdate
    if self.title_changed? || self.description_changed?
      self.statusupdates.create(
        :content => Texttemplate.substitute(:project_edit), :isPublic => true, 
        :user => nil, :html_tmpl_key => "EDIT")
    elsif self.status_changed?
      self.statusupdates.create(
        :content => Texttemplate.substitute(:project_status_edit, {"#status" => Project.parse_status(status)}), 
        :isPublic => true, :user => nil, :html_tmpl_key => "STATUS")
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :check_user_role
  filter_resource_access #authorization

  def index
    @status = Project.parse_status params[:status]
    # filter by category or status and sort
    @projects = Project.filter_projects(params[:category], params[:status]).is_public.sorted.paginate(:page => params[:page], :per_page => 15)
  end

  def show
    @owner = @project.roles.find_by_role :owner
    @count_images = @project.images.count
    @statusupdates = @project.statusupdates.sorted.paginate :page => params[:page], :per_page => 10
  end

  def edit
    @privacy = @project.privacy_setting
  end

  def update
    case params[:field]
      when 'info'
        params[:project][:category_ids] ||= {}
        @project.update_attributes params[:project]
      when 'status'
        @project.update_attributes params[:project]
    end
    
    respond_to do |format|
      format.js { render :nothing => true }
    end
  end

  def create
    @project.isInternal = true
    @project.status = "idea"
    if @project.save
      @role = Role.new(:role => "owner", :user => current_user, :project => @project, :job => params[:project][:role][:job])
      if @role.save
        redirect_to @project, :notice=>"Projekt wurde erfolgreich erstellt!" and return
      end
    end
    redirect_to :back, :error=>"Projekt konnte nicht erstellt werden!"
  end
  
  def follow
    @project = Project.find params[:id]
    @role = Role.new(:role => "follower", :user => current_user, :project => @project, :job => nil)
    if @role.save
      flash[:notice] = "Du beobachtest nun dieses Projekt. Aktuelle Statusupdates findest du in deinem Dashboard."
    else 
      flash[:notice] = "Es ist ein Fehler aufgetreten!" 
    end
    redirect_to @project and return
  end
  
  def unfollow
    @project = Project.find params[:id]
    @role = Role.where(:role => "follower", :user_id => current_user.id, :project_id => @project.id).first
    if @role.destroy
      flash[:notice] = "Du beobachtest dieses Projekt nun nicht mehr!"
    else 
      flash[:notice] = "Es ist ein Fehler aufgetreten!"
    end
    redirect_to @project and return
  end
  
  def leave
    @project = Project.find params[:id]
    @role = Role.where(:user_id => current_user.id, :project_id => @project.id).first
    if @role.destroy
      @project.team(true).each do |member|
        Notification.create( 
          :sender_id=>current_user.id, :receiver_id=>member.id, :project_id=>@project.id,
          :isNew=>true, :html_tmpl_key=>"USER_LEAVE")
      end
      Statusupdate.create(
        :content => Texttemplate.substitute(:team_delete, {"#user" => current_user.name}), :isPublic => true, :user_id => current_user.id,
        :project_id => @project.id, :html_tmpl_key => "TEAM_DELETE")
    else 
      flash[:notice] = "Fehler beim Versuch, das Projekt zu verlassen."
    end
    redirect_to :back and return
  end
  
  def join
    user_id = (params[:receiver_id].nil?) ? current_user.id : params[:receiver_id]
    success = false
    @project = Project.find params[:id]
    @old_role = Role.where(:user_id => user_id, :project_id => @project.id, :role => "follower").first
    if @old_role.nil?
      success = true if Role.create(:role => "member", :user_id => user_id, :project => @project)
    else
      success = true if @old_role.update_attributes :role => "member"
    end
    
    if success
      Notification.find(params[:notification_id]).destroy
      
      @project.team(true).where("user_id != ?", user_id).each do |member|
        Notification.create(
          :sender_id=>user_id, :receiver_id=>member.id, :project_id=>@project.id,
          :isNew=>true, :html_tmpl_key=>"USER_NEW")
      end
      if !params[:dtu]
        Notification.create(
          :sender_id=>@project.owner.id, :receiver_id=>user_id, :project_id=>@project.id,
          :isNew=>true, :html_tmpl_key=>"ACCEPTED_TO_USER")
      end
      
      Statusupdate.create(
        :content => Texttemplate.substitute(:team_new), :isPublic => true, :user_id => user_id,
        :project_id => @project.id, :html_tmpl_key => "TEAM")
       
      redirect_to :back and return
    else
      redirect_to :back, :error => "Es ist ein Fehler aufgetreten!"
    end
  end
  
  def apply
    if Notification.create(
        :sender_id=>current_user.id, :receiver_id=>@project.owner.id, :project_id=>@project.id,
        :isNew=>true, :html_tmpl_key=>"DECISION_TO_OWNER")
      redirect_to :back, :notice => "Die Bewerbung wurde verschickt!" and return
    end
    redirect_to :back, :error => "Die Bewerbung konnte leider nicht verschickt werden!"
  end
    
  def check_user_role
    if !params[:id].nil?
      current_user.current_role = current_user.roles.where(:project_id => params[:id])
    elsif params[:controller] == "media"
      current_user.current_role = current_user.roles.where(:project_id => params[:project_id])
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_dialog.html.erb
<div class="ajx"><div class="con">
  <div class="loading"><%= image_tag "loading.gif" %></div>
  <div class="ask">
    <p class="msg">Änderungen übernehmen?</p>
    <%= submit_tag "Übernehmen", :class=>"stdBtn" %>
    <a class="stdBtn no2 close"><p>Abbrechen</p></a>
  </div>
  <div class="success"><%= image_tag "ok.png" %></div>
</div></div>

app/views/projects/_info_form.html.erb
<div class="inline">
  <%= form_for @project, :remote => true, :id=>"infoform" do |f| %>
    <%= hidden_field_tag 'field', 'info' %>
    <%= render 'dialog' %>
    <div id="projecthead">
      <label>Titel:</label><br />
      <%= f.text_field :title, :class=>"eName" %>
      <br /><br /><label>Kategorien:</label><br />
      <%= select_tag :category, options_from_collection_for_select(Category.all.each, "id", "label"), :class=>"left", :id=>"formECat", :include_blank => 'Auswählen ...' %>
      <ul class="category">
        <script type="text/javascript">
        <% @project.categories.each do |c| %>
           <% cats = Category.where("label = ?", c.label).first.id %>
             catAdd('<%= cats %>', "<%= c.label %>");
           <% end %>
        </script>
      </ul>
      <div class="hide">
        <% Category.all.each do |category| %>
          <div><%= check_box_tag "project[category_ids][]", category.id, @project.categories.include?(category), :class=>"hiddencat" %></div>
        <% end %>
      </div>
      <br />
    </div>
    <label>Beschreibung:</label><br />
    <%= f.text_area :description, :class=>"eDescription" %>
    <%= render 'submit_buttons' %>
  <% end %>
</div>

app/views/projects/_jobs_form.html.erb
<div class="inline">
  <%= form_for @project, :remote => true do |f| %>
    <%= render 'dialog' %>
    <%= hidden_field_tag 'field', 'job' %>
    <br /><label>Neuer Job:</label><br />
    <%= text_field_tag :job, "", :class=>"eName" %>
    <a class="add"><%= image_tag "vor.png" %></a>
    <br class="clean" />
    <ul class="openjobs">
      <script type="text/javascript">
      <% @project.jobs.each do |j| %>
        jobAdd("<%= j.id %>", "<%= j.name %>", false);
      <% end %>
      </script>
    </ul>
     <div class="hide">
     <% @project.jobs.each do |job| %>
        <div>
         <%= check_box_tag "project[job_ids][]", job.id, @project.jobs, :class=>"hiddenjobs" %>
         <%= job.name %>
        </div>
      <% end %>
      <div class="newjobs">
      </div>
     </div>
    <%= render 'submit_buttons' %>
  <% end %>
</div>

app/views/projects/_overlay_form.html.erb
<div id="overlayCreateProject" class="overlay">
	<h1>Neues Projekt erstellen</h1>
	<a class="close" id="close"><%= image_tag 'close.png' %></a>
	<div class="content">
    <div id="npformular">
      <%= form_for Project.new, :url => { :controller => "projects", :action => "create" } do |f| %>
        <div class="inputfield">
          <%= f.label :title, "Titel" %><br/>
          <%= f.text_field :title, :class => "stdInpt", :placeholder => "Titel für ihr Projekt eingeben" %>
        </div>
        
        <div>
          <%= f.label :description, "Beschreibung" %>
          <%= f.text_area :description, :class => "description", :placeholder => "Kurzbeschreibung für ihr Projekt eingebenen" %>
        </div>
        
        <div>
          <%= f.label :category, "Kategorie" %><br/>
          <%= select_tag :category, options_from_collection_for_select(Category.all.each, "id", "label"), :id => "formECat", :include_blank => 'Auswählen ...' %><br/>
          <ul class="category">
            <script type="text/javascript">
              <% Project.new.categories.each do |c| %>
               <% cats = Category.where("label = ?", c.label).first.id %>
                 catAdd('<%= cats %>', "<%= c.label %>");
               <% end %>
            </script>
          </ul>
          <div class="hide">
            <% Category.all.each do |category| %>
              <div><%= check_box_tag "project[category_ids][]", category.id, Project.new.categories.include?(category), :class => "hiddencat" %></div>
            <% end %>
          </div>
        </div>
  
        <div>
          <%= f.label :isPublic, "Sichtbarkeit" %><br/>
          <%= f.check_box :isPublic, :checked => "checked", :class => "stdInpt" %> Projekt ist für alle sichtbar
        </div>
  
        <div>
          <%= f.label :job, "Tätigkeit" %><br/>
          <span class="username"><%= current_user.name %></span>
          <%= f.fields_for :role do |rf| %>
            <%= rf.text_field :job, :class => "stdInpt job", :placeholder => "Job"  %>
          <% end %>
        </div>
  
        <%= f.submit "Projekt erstellen", :class => "stdBtn no2" %>
      <% end %>
    </div>
    <div class="clean"></div>
	</div>
</div>

app/views/projects/_stages_form.html.erb
	<div class="inline">
    <%= form_for @project, :remote => true do |f| %>
      <%= hidden_field_tag 'field', 'stages' %>
      <%= render 'dialog' %>
      <br /><br />
    <label>Neue Stage:</label><br />
    <%= text_field_tag :stage, "", :class=>"eName" %>
    <a class="add"><%= image_tag "vor.png" %></a>
    <br class="clean" />
        <ul id="stagebar">
        <% @project.stages.order("position ASC").each do |s| %>
          <li sid="<%= s.id %>">
            <div>
            <%= text_field_tag "stages[name][]",s.name, :class=>"text" %>
            <%= hidden_field_tag "stages[position][]",s.position, :class=>"pos" %>
            <%= hidden_field_tag "stages[sid][]",s.id, :class=>"ysid" %>
            </div>
            <a class="delete"><%= image_tag("delete.png") %></a>
          </li>
        <% end %>
        </ul>
        <div class="hide">
        <% @project.stages.order("position ASC").each do |st| %>
           <%= check_box_tag "project[stage_ids][]", st.id, @project.stages.include?(st), :class=>"hiddenstages" %>
          <% end %>
          <div class="newstages">
          </div>
        </div>
     <br />
   <label>Aktuelle Stage:</label><br />
   <%= select_tag "crrent", options_for_select(@project.stages.collect{ |s| [s.name, s.position, :sid=>s.id] }, @project.currentstage) %>
<div class="clean hide"></div>
     
     <%= render 'submit_buttons' %>
   <% end %>
	</div>

app/views/projects/_status_form.html.erb
<div class="inline">
  <%= form_for @project, :remote => true do |f| %>
    <%= hidden_field_tag 'field', 'status' %>
    <%= render 'dialog' %>
    <br /><br />
    <label>Status:</label><br />
    <%= select "project", "status", options_for_select([['Idee','idea'],['In Arbeit','inprogress'],['Abgeschlossen','finished']], @project.status), :class=>"left", :id=>"formEStatus" %>
    <div class="clean hide"></div>
    <%= render 'submit_buttons' %>
  <% end %>
</div>

app/views/projects/_submit_buttons.html.erb
<div class="clean hide"></div>
<a class="stdBtn asksubmit"><p>Speichern</p><%= image_tag "saveit.png" %></a>

app/views/projects/category.html.erb
<%= render 'layouts/sidebar_sorting' %>
<%= render 'projects' %>

app/views/projects/edit.html.erb
<%= render 'layouts/sidebar_sorting' %>

<div id="projectdetails">
  <div id="topbar">
    <%= link_to @project, :class=>"stdBtn" do %><p>Zurück zum Projekt</p><%= image_tag "back.png" %></a><% end %>
    <%= link_to "javascript:overlay('#overlayPrivacy');", :class=>"stdBtn no3" do %><p>Sichtbarkeit</p><%= image_tag "editit.png" %></a><% end %>
  </div>

  <div id="projectinfo">
    <%= render "info_form" %>
  </div>
  <div id="projectcover">
	   <%= render "media/cover_upload_form" %>
	</div>
</div>

<div id="rightbar">
  <!-- STATUS -->
  <div id="projectstate">
    <h5 class="noedit">Projektstatus</h5>
    <%= render "status_form" %>
  </div>
  
  <!-- PROGRESS -->
  <div id="projectprogress">
    <h5 class="noedit">Stages</h5>
    <%= render "stages/edit_form" %>
  </div>

  <!-- JOBS -->
  <div id="searchingmember">
    <h5 class="noedit">Auf der Suche nach <span>(<%= @project.jobs.count %>)</span></h5>
    <%= render "jobs/edit_form" %>
  </div>

  <!-- TEAM -->
  <div id="teammember">
    <h5 class="noedit">Team <span>(<%= @project.has_members.count %>)</span></h5>
    <%= render "roles/edit_form" %>
  </div>
</div>

<!-- OVERLAY -->
<div id="overlayPrivacy" class="overlay">
  <h1>Sichtbarkeit</h1>
  <a class="close" id="close"><%= image_tag 'close.png' %></a>
  <div class="content">
    <%= form_for @project do |f| %>
          <%= f.check_box :isPublic %><%= f.label :isPublic, "Updates sichtbar?" %>
          <br />
      <%= f.submit %>
    <% end %>
    <div class="clean"></div>
  </div>
</div>

app/views/projects/index.html.erb
<%= render 'layouts/sidebar_sorting' %>

<div id="overview" class="start">
  <% if !params[:category].nil? || !params[:status].nil? %>
    <p class="stdNotice info">
      <%= link_to image_tag("close-notice.png"), Project, :class=>"right" %>
      <% if !params[:category].nil? %>
        <%= params[:category] %>
        <%= image_tag "arrow-notice.png" %>
      <% end %>
      <% if !params[:status].nil? %>
        <%= params[:status] %>
        <%= image_tag "arrow-notice.png" %>
      <% end %>
      <b><%= @projects.count %></b> Projekt<% if @projects.size>1 || @projects.size==0 %>e<% end %>
    </p>
  <% end %>

  <% @projects.each do |p| %>
	<div class="boxcontent">
	  <div class="projectcategory mmt"><% if p.categories.any? %> <%= p.categories.first.label %> <% end %></div>
	  <div class="icon"><% if p.jobs.any? %><%= image_tag "statussearch.png" %><% end %></div>
	  <div class="projectinfo">
      <%= link_to image_tag(p.cover_url), p, :class=>"cover" %>
      <h3><%= trimString p.title, 30 %></h3>
      <p class="infotxt"><%= trimString p.description, 225 %></p>
      <% link_to p, :class =>'details' do image_tag "details-arrow.png" end %>
	  </div>
	  <div class="projectadmin">
      <p class="left">von <%= link_to p.owner.name, p.owner %></p>
      <p class="right"><b><%= p.has_followers.count %></b> Beobachter</p>
	  </div>
	</div>
  <% end %>
  <div class="clean"></div>
  <%= will_paginate @projects %>

  <% if @projects.empty? %>
	<p class="nodisplay"><i>Keine Projekte vorhanden &hellip;</i></p>
  <% end %>
</div>

app/views/projects/show.html.erb
<%= render 'layouts/sidebar_sorting' %>

<div id="projectdetails">
  <div id="topbar">
    <% if @project.jobs.any? %><%= image_tag "statussearch.png", :class=>"left" %><% end %>
    <div class="btns">
      <% if permitted_to? :follow, @project %>
        <%= link_to follow_project_path(@project), :method => :put, :class=>"stdBtn" do %>
          <p>Beobachten</p><%= image_tag "spec.png" %>
        <% end %>
      <% end %>
      <% if permitted_to? :unfollow, @project %>
        <%= link_to unfollow_project_path(@project), :method => :delete, :class=>"stdBtn" do %>
          <p>nicht mehr Beobachten</p><%= image_tag "nospec.png" %>
        <% end %>
      <% end %>
      <% if permitted_to? :leave, @project %>
        <%= link_to leave_project_path(@project), :method => :delete, :class=>"stdBtn" do %>
          <p>Projekt verlassen</p><%= image_tag "noapply.png" %>
        <% end %>
      <% end %>
      <% if (permitted_to? :apply, @project) && (current_user.can_apply? @project) %>
        <%= link_to apply_project_path(@project), :method => :post, :class=>"stdBtn" do %>
          <p>Bewerben</p><%= image_tag "apply.png" %>
        <% end %>
      <% end %>
      <% if permitted_to? :edit, @project %>
        <%= link_to edit_project_path, :class=>"stdBtn" do %><p>Bearbeiten</p><%= image_tag "editit.png" %><% end %>
        <%= link_to "javascript:overlay('#overlaySendInvitation');", :class=>"stdBtn" do %><p>User einladen</p><%= image_tag "apply.png" %></a><% end %>
      <% end %>
      <% if permitted_to? :create, @project.media.new %>
        <%= link_to "javascript:overlay('#overlayMediaUpload');", :class=>"stdBtn" do %><p>Medien hochladen</p><%= image_tag "new.png" %></a><% end %>
      <% end %>
    </div>
  </div>
  <div class="center">
    <div id="projectinfo">
      <div class="edit">
        <div id="projecthead">
          <h5><%= @project.title %></h5>
        </div>
        <%= image_tag @project.cover_url, :class=>"image" %>
        <ul class="category">
            <% @project.categories.each do |c| %>
              <li><%= c.label %></li>
            <% end %>
          </ul>
        <div class="desc"><%= simple_format @project.description %></div>
      </div>
    </div>
  </div>
  <div class="getleft">
    <div id="updates">
      <h5 class="noedit">Statusupdates <span>(<%= @project.statusupdates.count %>)</span></h5>
      <% if permitted_to? :new, Statusupdate.new %>
        <%= render :partial => "statusupdates/form" %>
      <% end %>
      <br/>
      <ul id="stdProjectStatusUpdates">
        <% @statusupdates.each do |su| %>
          <% case su.html_tmpl_key %>
            <% when 'POST' %>
              <li class="post">
                <%= link_to image_tag(avatar_url(su.user, 40)), su.user, :class=>"pic" %>
                <p><%= link_to su.user.name, su.user %><br/>&#132;<%= su.content %>&#147;</p>
                <sub><%= formatDate su.created_at, true, true %></sub>
              </li>
            <% when 'EDIT' %>
              <li class="line"><%= image_tag 'tny-edit.png' %><%=raw su.content %><sub><%= formatDate su.created_at, true, true %></sub></li>
            <% when 'STATUS' %>
              <li class="status"><%=raw su.content %><sub><%= formatDate su.created_at, true, true %></sub></li>
            <% when 'JOBS' %>
              <li class="jobs"><%=raw su.content %><sub><%= formatDate su.created_at, true, true %></sub></li>
            <% when 'JOBS2' %>
              <li class="jobs2"><%=raw su.content %><sub><%= formatDate su.created_at, true, true %></sub></li>
            <% when 'MEDIA' %>
              <li class="line2"><%=raw su.content %><sub><%= formatDate su.created_at, true, true %></sub></li>
            <% when 'TEAM' %>
              <li class="team"><%= link_to image_tag(avatar_url(su.user, 20)), su.user, :class=>"pic" %><%= link_to su.user.name, su.user %> <%=raw su.content %><sub><%= formatDate su.created_at, true, true %></sub></li>
            <% when 'TEAM_DELETE' %>
              <li class="team2"><%= link_to image_tag(avatar_url(su.user, 20)), su.user, :class=>"pic" %><%= link_to su.user.name, su.user %> <%=raw su.content %><sub><%= formatDate su.created_at, true, true %></sub></li>
          <% end %>
        <% end %>
        <% if @statusupdates.empty? %>
          <p class="nodisplay"><i>Keine Statusupdates &hellip;</i></p>
        <% end %>
      </ul>
      <div class="clean hide"></div>
      <%= will_paginate @statusupdates %>
    </div>
  
    <div id="media">
      <h5 class="noedit">Medien <span>(<%= @count_images %>)</span></h5>
      <% if @project.images.any? %>
          <% if @count_images > 5 %><a class="prev"><%= image_tag 'left.png' %></a><% end %>
          <div class="mediaslider">
          <ul>
            <% @project.images.sorted.each do |m| %>
              <li><%= link_to (image_path m.asset.url(:original)) do image_tag m.asset.url(:medium) end %></li>
            <% end %>
          </ul>
          </div>
          <% if @count_images > 5 %><a class="next"><%= image_tag 'right.png' %></a><% end %>
          <br class="clean" /><br />
          <%= link_to [ @project, :media ], :class=>"stdBtn" do %><p>Alle Medien ansehen</p><%= image_tag "details-arrow.png" %></a><% end %>
      <% end %>
    </div>
  </div>
</div>
<%= render 'rightbar' %>
<!-- UPLOAD OVERLAY-->
<% if permitted_to? :create, @project.media.new %>
  <%= render :partial => 'media/upload_form', :locals => { :multiple_queues => true } %>
<% end %>
<% if permitted_to? :edit, @project %>
  <%= render 'notifications/invitation_form' %>
<% end %>