config/routes.rb
Projektplattform::Application.routes.draw do
  get "notifications/index"
  get "statusupdates/index"

  devise_for :users
  
  resources :users
  resources :searchs
  resources :dashboards
  resources :statusupdates
  resources :roles
  resources :stages
  resources :notifications do
    collection do
      put :mark_as_read
    end
  end
  resources :jobs
    
  resources :projects do
    member do
      put :follow
      delete :unfollow
      delete :leave
      put :join
      post :apply
    end
    resources :media
  end
  
  root :to => "projects#index"

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @statusupdates = Statusupdate.dashboard(current_user).paginate(:page => params[:page], :per_page => 20)
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_sidebar.html.erb
<div id="rightbar">
	<div id="dashboardhead"> 
      <div class="me">
	      <%= link_to image_tag(avatar_url(current_user, 56)), current_user, :class=>"left" %>
          <%= link_to current_user.name, current_user, :class=>"name" %><br/>
          <%= link_to "Mein Profil", current_user, :class=>"stdBtn" %>
      </div>
      <div class="inf">
        <p><sub>LETZTER LOGIN:<br/><span><%= formatDate current_user.last_sign_in_at, true %></span></sub><br/><br/>
        <sub>DABEI SEIT:<br/><span><%= formatDate current_user.created_at %></span></sub></p>
      </div>
      <div class="clean"></div>
      <%= link_to "javascript:overlay('#overlayNotifications');", :class=>"stdBtn countme tip" do %>
        <%= image_tag "not.png" %>
        <% if User.count_unread_notifications(current_user)  > 0 %><sup class="count"><%= User.count_unread_notifications current_user %></sup><% end %>
        <div class="hide tool">Notifications<%= image_tag "arrdown.png" %></div>
      <% end %>
      <%= link_to "javascript:overlay('#overlayCreateProject');", :class=>"stdBtn tip" do %>
        <%= image_tag "new.png" %>
        <div class="hide tool">Neues Projekt<%= image_tag "arrdown.png" %></div>
      <% end %>
      <%= link_to edit_user_path(current_user), :class=>"stdBtn tip" do %>
        <%= image_tag "editit.png" %>
        <div class="hide tool">Profil bearbeiten<%= image_tag "arrdown.png" %></div>
      <% end %>
      <%= link_to destroy_user_session_path, :class=>"stdBtn no2", :style=>"margin: 0 0 0 12px;" do %><span>Logout</span><% end %>
      <div class="clean"></div>
	</div>

	<div id="myproject">
		<h2>Projekte in Arbeit</h2>
		<% if current_user.running_projects.any? %>
			<% current_user.running_projects.each do |p| %>
				<div class="project">
				<%= link_to image_tag(p.icon_url), p, :class=>"pic" %>
				<p><%= link_to p.title, p %><br><span class="sl"><%= p.has_members.count %> Mitarbeiter</span></p>
				</div>
		<% end else %>
		<p class="nodisplay"><i>Keine Projekte in Arbeit &hellip;</i></p>
		<% end %>
	</div>

	<div id="followprojects">
		<h2>beobachtete Projekte</h2>
		<% if current_user.following_projects.any? %>
			<% current_user.following_projects.each do |p| %>
		  <div class="project">
			<%= link_to image_tag(p.icon_url), p, :class=>"pic" %>
			<p><%= link_to p.title, p %><br><span class="sl"><%= p.has_members.count %> Mitarbeiter</span></p>
		  </div>
		<% end else %>
		<p class="nodisplay"><i>Keine beobachteten Projekte &hellip;</i></p>
		<% end %>
	</div>
</div>

app/views/dashboards/index.html.erb
<%= render 'layouts/sidebar_sorting' %>

<div id="dashboardarea">
	<ul id="stdProjectStatusUpdates">
	  <% @statusupdates.each do |su| %>
      <li class="dash">
        <div class="proj">
           <%= link_to su.project.title, su.project, :class=>"title" %>
           <%= link_to image_tag(su.project.icon_url), su.project, :class=>"pic" %><br />
		  <% case su.html_tmpl_key %>
        <% when 'POST' %>
          <div class="post">
            <p><%= link_to su.user.name, su.user %>: &#132;<%= su.content %>&#147;</p>
        <% when 'EDIT' %>
          <div class="line"><%= image_tag 'tny-edit.png' %><%=raw su.content %>
        <% when 'STATUS' %>
          <div class="status"><%=raw su.content %>
        <% when 'JOBS' %>
          <div class="jobs"><%=raw su.content %>
        <% when 'JOBS2' %>
          <div class="jobs2"><%=raw su.content %>
        <% when 'MEDIA' %>
          <div class="line2"><%=raw su.content %>
        <% when 'TEAM' %>
          <div class="team"><%= link_to su.user.name, su.user %> <%=raw su.content %>
        <% when 'TEAM_DELETE' %>
          <div class="team2"><%= link_to su.user.name, su.user %> <%=raw su.content %>
		  <% end %>
        <sub><%= formatDate su.created_at, true, true %></sub>
		</div></div>
      </li>
		<% end %>
  </ul>
  <% if @statusupdates.empty? %>
    <p class="nodisplay"><i>Keine Statusupdates &hellip;</i></p>
  <% end %>
  <div class="clean hide"></div>
  <%= will_paginate @statusupdates %>
</div>

<%= render 'sidebar' %>
<%= render 'projects/overlay_form' %>